_schema: _schema
paths:
  uploads: static/uploads
  static: static
collections_config:
  pages:
    path: ''
    name: Pages
    icon: wysiwyg
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_config:
    path: src/config
    name: Src Config
    icon: ac_unit
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_content_about:
    path: src/content/about
    name: Src Content About
    icon: content_cut
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_content_authors:
    path: src/content/authors
    name: Src Content Authors
    icon: recent_actors
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_content_blog:
    path: src/content/blog
    name: Src Content Blog
    icon: account_box
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_content_contact:
    path: src/content/contact
    name: Src Content Contact
    icon: content_copy
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_content_homepage:
    path: src/content/homepage
    name: Src Content Homepage
    icon: contact_page
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_content_pages:
    path: src/content/pages
    name: Src Content Pages
    icon: contact_page
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
  src_content_sections:
    path: src/content/sections
    name: Src Content Sections
    icon: content_copy
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
timezone: Asia/Dhaka
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
